/**
 * Site Signals — every action taken on hutchrok.com, normalized.
 *
 * The site (FeeTheDeveloper/hutchrok_solutions-site) emits one signed signal
 * per business action to POST /api/v1/site/signals. The autopilot turns each
 * signal into an OS event plus the actions defined in its playbook.
 */

import { z } from 'zod';

export const SITE_SIGNAL_TYPES = [
  'contact.submitted',
  'lead.created',
  'intake.submitted',
  'service_request.submitted',
  'federal_intake.submitted',
  'case.created',
  'case.status_changed',
  'case.event',
  'document.uploaded',
  'payment.completed',
  'payment.failed',
  'membership.activated',
  'account.created',
  'site.other',
] as const;

export type SiteSignalType = (typeof SITE_SIGNAL_TYPES)[number];

export const SiteContactSchema = z.object({
  name: z.string().max(200).optional(),
  email: z.string().email().max(320).optional(),
  phone: z.string().max(40).optional(),
  businessName: z.string().max(200).optional(),
});

export type SiteContact = z.infer<typeof SiteContactSchema>;

export const SiteSignalSchema = z.object({
  /** Idempotency key generated by the site — replays are ignored. */
  signalId: z.string().min(8).max(200),
  type: z.enum(SITE_SIGNAL_TYPES),
  occurredAt: z.string().datetime(),
  source: z.string().max(100).default('hutchrok.com'),
  contact: SiteContactSchema.optional(),
  subject: z.string().max(300).optional(),
  message: z.string().max(10_000).optional(),
  entity: z
    .object({
      type: z.string().max(60),
      id: z.string().max(200).optional(),
      ref: z.string().max(200).optional(),
    })
    .optional(),
  data: z.record(z.unknown()).default({}),
});

export type SiteSignal = z.infer<typeof SiteSignalSchema>;

/** Map a site signal type to the canonical OS event type. */
export function osEventTypeFor(type: SiteSignalType): string {
  switch (type) {
    case 'contact.submitted':
      return 'message.received';
    case 'lead.created':
      return 'lead.created';
    case 'intake.submitted':
      return 'intake.completed';
    case 'case.created':
      return 'filing.created';
    case 'document.uploaded':
      return 'document.uploaded';
    case 'payment.completed':
      return 'payment.completed';
    case 'payment.failed':
      return 'payment.failed';
    default:
      return `site.${type}`;
  }
}
